version: "3.9"
services:
    web:
        build: .
        ports:
            - "8000:8000"
        command: python my_project/manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/django_pro
